### ISSUE TITLE
Curvenote init / start results in `command failed`

### ISSUE THREAD

**Issue by choldgraf** [curvenote/curvenote#293] opened 2022-07-31 12:00 UTC
I was just trying to experiment with the curvenote CLI, following [the curvenote docs](https://curvenote.com/docs/cli/installing). However, when I did the following:

- `npm install -g curvenote`
- `mkdir tmp; cd tmp`
- `curvenote init`
- `curvenote start`

I got the following NPM error. Curious if I am doing something wrong here...

```
        ✨✨✨  Starting Curvenote  ✨✨✨


/tmp/serve-41132377.sh: 1: /tmp/serve-41132377.sh: cross-env: not found
npm ERR! Lifecycle script `serve` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @curvespace/default@0.0.6
npm ERR!   at location: /home/choldgraf/github/forks/python/ebp/tmp/_build/curvenote/apps/web

Command failed: npm run serve
/tmp/serve-41132377.sh: 1: /tmp/serve-41132377.sh: cross-env: not found
npm ERR! Lifecycle script `serve` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @curvespace/default@0.0.6
npm ERR!   at location: /home/choldgraf/github/forks/python/ebp/tmp/_build/curvenote/apps/web
```

**Comment by rowanc1** [comment] 2022-07-31 16:44
Thanks for the report! All looks correct.

What node version are you on?
`node -v`

**Comment by choldgraf** [comment] 2022-07-31 18:40
Here's what I've got:

```
$ npm -v
8.15.1

$ node -v
v14.18.3
```

I am a total JS noob so might have done something wrong

**Comment by rowanc1** [comment] 2022-07-31 19:26
Huh, those should be supported, I will try to dig in a bit more early next week.

**Comment by rowanc1** [comment] 2022-07-31 19:38
Must be that we are missing the `cross-env` dependency. Not sure why I haven't come into that before.

**Comment by choldgraf** [comment] 2022-07-31 20:15
Guess that's the challenge of npm -g 🤷

**Comment by stevejpurves** [comment] 2022-08-04 19:50
@choldgraf diving into this - quick question which OS are you running this on?

**Comment by choldgraf** [comment] 2022-08-04 20:09
Windows 11, using windows subsystem for Linux (which I believe is Ubuntu)

**Comment by rowanc1** [comment] 2022-08-05 15:46
@stevejpurves is expanding some of our integration testing on windows. I think there are some other issues out there with the `crossenv` package specifically (which is a bit ironic). I have removed that dependency from the start command in #297.

We will continue to test on our side, but if either you or @sakelariev want to test it, the following command should work now (as long as npm>=7). The `-f` reinstalls the web dependencies.

```bash
curvenote start -f
```

We have also improved the messaging around the npm version which needs to be >7 (not @choldgraf's issue specifically, but maybe related). That is released in `curvenote@0.6.17`.

Will leave this open to hear from you, thanks for your help!

**Comment by choldgraf** [comment] 2022-08-06 12:33
hmmm, I'm now on 0.6.18 and tried from a fresh folder, but now I can't seem to create a template book? Here's what I see when I do `curvenote init`:

![image](https://user-images.githubusercontent.com/1839645/183249083-e40b9630-5399-4677-9ef1-40ca6649af76.png)

Is my only option to first create something on curvenote?

**Comment by rowanc1** [comment] 2022-08-06 17:14
The first option will provide some defaults after you press enter, so not necessary to create on curvenote first. Good point to include some other examples there though to make this clearer.

Also if you start in a folder with content (e.g. existing book or similar) it will use that instead and the second option won't be disabled.

I will do a pass here to improve that!

**Comment by choldgraf** [comment] 2022-08-06 17:33
Ah gotcha - i think by having the option of "example content" explicitly listed as disabled, i assumed all other options would not include example content

**Comment by choldgraf** [comment] 2022-08-06 17:34
Ah gotcha - i think by having the option of "example content" explicitly listed as disabled, i assumed all other options would not include example content

**Comment by choldgraf** [comment] 2022-08-06 18:47
Hmmm now I am getting another strange logs error. Here's the full output:

```
Starting local server with:  curvenote start
🌎 Cloning Curvenote
⤵️  Installing web libraries (can take up to 60 s)
📦 Installed web libraries in 40 s
🛠 Built dependencies in 4.93 s
🧹 Clean build files in 367 μs.
🏫 Read 2 citations from content/web/references.bib in 63 ms.
📖 Built content/web/index.md in 446 ms.
📖 Built content/web/notebook.ipynb in 439 ms.
📖 Built content/web/background.md in 494 ms.
📚 Built 3 pages for web in 576 ms.
⚙️  Writing site config.json


        ✨✨✨  Starting Curvenote  ✨✨✨


⚡️ Compiled in 1510ms.
🚀 Built in 1.7s
Error: getaddrinfo ENOTFOUND x86_64-conda-linux-gnu
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)

npm ERR!
 Lifecycle script `serve` failed with error:
npm ERR!
 Error: command failed

npm ERR!   in workspace: @curvespace/default@0.0.7
npm ERR!   at location: /home/choldgraf/github/forks/python/ebp/tmp/curvenote/_build/curvenote/apps/web
Command failed: npm run serve

Done in 1510ms.
The path "@heroicons/react/outline" is imported in ../../packages/site/src/components/FooterLinksBlock.tsx but @heroicons/react is not listed in your package.json dependencies. Did you forget to install it?
Error: getaddrinfo ENOTFOUND x86_64-conda-linux-gnu
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
npm ERR! Lifecycle script `serve` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @curvespace/default@0.0.7
npm ERR!   at location: /home/choldgraf/github/forks/python/ebp/tmp/curvenote/_build/curvenote/apps/web



Curvenote CLI Versions:
 - node                        14.18.3     Required: >= 14.0.0      ✅
 - npm                          8.15.1     Required: >=7            ✅
 - curvenote                    0.6.18
 - @curvespace/default           0.0.7
```

**Comment by stevejpurves** [comment] 2022-08-08 09:17
@choldgraf that is indeed a strange one. Looks like it is attempting to reach `x86_64-conda-linux-gnu` instead of `localhost`.

I can reproduce your error by running `HOST=some-random-name curvenote start` i.e. you may have `HOST=x86_64-conda-linux-gnu` set in your environment. try `echo $HOST` to confirm that.

And until we can patch this, try either:

```HOST=localhost PORT=3000 curvenote start```

or unset the `HOST` environment variable:

```
unset HOST
curvenote start
```

I think we should release a patch that either warns when this is not `localhost` or ignores it.

**Comment by stevejpurves** [comment] 2022-08-08 09:19
@sakelariev if you've also hit this issue, could you please share which platform you're running on? 🙏

**Comment by choldgraf** [comment] 2022-08-08 11:20
oooh that got it working!

Feel free to close this issue if you think there's nothing obviously actionable remaining

**Comment by rowanc1** [comment] 2022-08-08 14:30
I have recorded the actionable followups in #302 and #187.

Thanks for helping debug this @choldgraf!

**Closed as completed by rowanc1** 2022-08-08 14:30 UTC
Labels: bug

**Comment by stevejpurves** [comment] 2022-08-08 21:25
great! thanks @choldgraf and glad you are up and running
